version: "2"
services:
  db:
    image: mysql:5.7.28
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    ports:
      - 3406:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    image: inner_join_cc
    environment:
      - LANG=C.UTF-8
    tty: true
    volumes:
      - .:/inner_join_cc
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  bundle:
  db-data:
